version: '3.6'

services:
  traefik:
    image: traefik:v2.2
    container_name: "traefik${CONTAINER_SUFFIX:-}"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    environment:
      - ACME_DOMAIN=${ACME_DOMAIN}
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/traefik.yml:/etc/traefik/traefik.yml:ro
      - type: bind
        source: ./data/user.secrets
        target: /etc/traefik/user.secrets
        read_only: true
      - type: bind
        source: ./data/acme.json
        target: /etc/traefik/acme.json
    labels:
      - "traefik.enable=true"

networks:
  proxy:
    name: ${NETWORK_NAME:-proxy}
